# Form implementation generated from reading ui file '.\Metronome_mainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(277, 488)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.dial = QtWidgets.QDial(parent=self.centralwidget)
        self.dial.setGeometry(QtCore.QRect(60, 120, 141, 161))
        self.dial.setObjectName("dial")
        self.pushButton_start = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_start.setGeometry(QtCore.QRect(80, 380, 75, 24))
        self.pushButton_start.setObjectName("pushButton_start")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(70, 260, 31, 21))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(170, 260, 31, 21))
        self.label_2.setObjectName("label_2")
        self.gridLayoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(60, 20, 160, 80))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 0, 1, 1)
        self.lineEdit_bmp = QtWidgets.QLineEdit(parent=self.gridLayoutWidget)
        self.lineEdit_bmp.setObjectName("lineEdit_bmp")
        self.gridLayout.addWidget(self.lineEdit_bmp, 0, 1, 1, 1)
        self.lineEdit_beat_num = QtWidgets.QLineEdit(parent=self.gridLayoutWidget)
        self.lineEdit_beat_num.setObjectName("lineEdit_beat_num")
        self.gridLayout.addWidget(self.lineEdit_beat_num, 1, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(30, 330, 33, 20))
        self.label_5.setObjectName("label_5")
        self.horizontalSlider_volume = QtWidgets.QSlider(parent=self.centralwidget)
        self.horizontalSlider_volume.setGeometry(QtCore.QRect(70, 330, 160, 18))
        self.horizontalSlider_volume.setMaximum(100)
        self.horizontalSlider_volume.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.horizontalSlider_volume.setObjectName("horizontalSlider_volume")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 277, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Metronome"))
        self.pushButton_start.setText(_translate("MainWindow", "开始"))
        self.label.setText(_translate("MainWindow", "30"))
        self.label_2.setText(_translate("MainWindow", "240"))
        self.label_3.setText(_translate("MainWindow", "BMP "))
        self.label_4.setText(_translate("MainWindow", "拍数"))
        self.lineEdit_beat_num.setText(_translate("MainWindow", "4"))
        self.label_5.setText(_translate("MainWindow", "音量"))
